### ISSUE TITLE
Windows Backend Start Problem

### ISSUE THREAD

**Issue by Bebdor** [dev-lu/osint_toolkit#24]
Console output:

PS C:\Users\Bebdor\Documents\osint_toolkit\backend> py -m uvicorn main:app
Traceback (most recent call last):
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3280, in _wrap_pool_connect
    return fn()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 476, in checkout
    rec = pool._do_get()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\impl.py", line 256, in _do_get
    return self._create_connection()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 371, in __init__
    self.__connect()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\__main__.py", line 4, in <module>
    uvicorn.main()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 408, in main
    run(
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Bebdor\Documents\osint_toolkit\backend\.\main.py", line 3, in <module>
    from routers import internal, external
  File "C:\Users\Bebdor\Documents\osint_toolkit\backend\.\routers\internal.py", line 15, in <module>
    models.Base.metadata.create_all(bind=engine)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\schema.py", line 4889, in create_all
    bind._run_ddl_visitor(
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3146, in _run_ddl_visitor
    with self.begin() as conn:
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3062, in begin
    conn = self.connect(close_with_result=close_with_result)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3234, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 96, in __init__
    else engine.raw_connection()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3313, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3283, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 2117, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3280, in _wrap_pool_connect
    return fn()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 476, in checkout
    rec = pool._do_get()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\impl.py", line 256, in _do_get
    return self._create_connection()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 371, in __init__
    self.__connect()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
PS C:\Users\Bebdor\Documents\osint_toolkit\backend>

Im using the newest version.

**Comment by Bebdor** [comment]
Ah, thanks mate!
I have been waiting for 4 days :) @dev-lu

**Comment by dev-lu** [comment]
Hey, sorry I'm pretty busy at the moment. This error usually occurs when the application cannot write to the `backend/database/data` folder. Make sure that this folder exists. Otherwise, I recommend installing using Docker, as this is usually more trouble-free.

**Comment by Bebdor** [comment]
I just created a "data" directory in "backend/database/".

The new Console Output:

Traceback (most recent call last):
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\__main__.py", line 4, in <module>
    uvicorn.main()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 408, in main
    run(
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\Bebdor\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Bebdor\Documents\osint_toolkit\backend\.\main.py", line 3, in <module>
    from routers import internal, external
  File "C:\Users\Bebdor\Documents\osint_toolkit\backend\.\routers\external.py", line 4, in <module>
    import ioc_analyzer
  File "C:\Users\Bebdor\Documents\osint_toolkit\backend\.\ioc_analyzer.py", line 255
    match scan_response.status_code:
          ^
SyntaxError: invalid syntax

**Comment by Bebdor** [comment]
How can I install it using docker?

**Comment by dev-lu** [comment]
Docker installation:

1. Download the repository and extract the files
2. Navigate to the directory where the docker-compose.yaml file is located and edit the file to your needs
3. If you deploy the app on a remote machine, set the BACKEND_URL argument in the Compose file to the remote machines IP address
4. Run the following command: docker-compose up -d
5. Once the container is running, you can access the app in your browser at http://localhost:3000

The installation via Docker is the recommended method, as all dependencies must fit exactly for a manual installation and this is usually not the case.

**Comment by Bebdor** [comment]
Got it. Thanks!
